Deliverable 1
edcolcode/2022React-Bootcamp-CapstoneProject pull request #1
Opened 2022-06-06 23:27 UTC by edcolcode

2022-06-07 22:02 UTC, ssanchezg requested changes
great Work, thanks for you effort and clean work, I would like to said I like what you do, also I saw you're pulling the data from the file as requested.

advice for the next delivery, remember all the tips, and deliveries can be updated, all the delivery dates are an advice dates, but we could modify, update or make changes on our code libs etc... the final delivery is the one who will be not posible to make changes after the delivery

1 .- the grids where you're showing the images and details with prices, the data it over the image in some ones and in another not, it could be a good idea  to set the detail under the image

2.- the footer is not displayed, this could be because in the app.js file, when we're doing the return the footer its outside of the Master Div, remember we could just return one Object.

3.- in the header the icon/name is to short, and seems like is cuting off the name, and all the objects are kind of too faraway each other., we could set a 3column and try to make them a little bit close and separate from the right or left side of the window.

2022-06-08 01:46 UTC, edcolcode commented
Hi @ssanchezg thanks for your comments. I did the required changes. Updated demo can be visualized now: https://deploy-preview-1--vermillion-frangipane-7e536b.netlify.app/

About the footer. Probably you did not see it due it was hidden by the deploy toolbar from Netlify
![image](https://user-images.githubusercontent.com/1985694/172513540-7142ba88-a017-4577-9ba7-a4ce06f611ee.png)

2022-06-08 15:59 UTC, ssanchezg commented
just amazing!!!!, super approved, thanks for the quick updates @edcolcode!!!

2022-06-08 16:01 UTC, ssanchezg approved these changes

2022-06-11 19:46 UTC, merged